### ISSUE TITLE
Terraform state out of sync

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/infra#14]
Previously discussed in https://github.com/nextstrain/infra/pull/10#discussion_r1619255328

I'm seeing changes in the Terraform plan even though I'm starting with a fresh clone of the repo and on the main branch. 

```
AWS_PROFILE=admin envdir ~/Repos/env.d/infra-github-token/ terraform -chdir=env/production init
AWS_PROFILE=admin envdir ~/Repos/env.d/infra-github-token/ terraform -chdir=env/production plan -out=plan
...
Plan: 38 to add, 0 to change, 4 to destroy.
```
[plan.txt](https://github.com/user-attachments/files/15680137/plan.txt)

**Comment by victorlin** [comment]
I can't seem to open the file linked in the issue description. Here's my output with `terraform plan -no-color`:

[plan.txt](https://github.com/user-attachments/files/15681935/plan.txt)

**Comment by joverlee521** [comment]
@victorlin Weird, I can't read your file either
```
$ terraform show ~/Downloads/plan.txt
╷
│ Error: Failed to read the given file as a state or plan file
│ 
│ State read error: Error reading /Users/joverlee/Downloads/plan.txt as a statefile: 2 problems:
│ 
│ - Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
│ - Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
│ 
│ Plan read error: couldn't load the provided path as either a local plan file (zip: not a valid zip file) or a saved cloud plan (invalid
│ character 'd' looking for beginning of value)
```

**Comment by victorlin** [comment]
Oh... I didn't realize `plan.txt` referred to the actual plan file used for `terraform show`, I thought it was just the full output. Now we have both – mine is the console output of `terraform plan` and yours is the `plan` file.

**Comment by joverlee521** [comment]
Terraform reading...

The "add" plans are [resources that rely on Terraform state](https://developer.hashicorp.com/terraform/language/resources/behavior#how-terraform-applies-a-configuration):

>When Terraform creates a new infrastructure object represented by a resource block, the identifier for that real object is saved in Terraform's [state](https://developer.hashicorp.com/terraform/language/state), allowing it to be updated and destroyed in response to future changes.

[Terraform state](https://developer.hashicorp.com/terraform/language/state):

> This state is stored by default in a local file named "terraform.tfstate", but we recommend [storing it in HCP Terraform](https://developer.hashicorp.com/terraform/cloud-docs/migrate) to version, encrypt, and securely share it with your team.

We are currently excluding the local state file from version control in the .gitignore

**Comment by joverlee521** [comment]
```
$ AWS_PROFILE=admin aws s3 ls s3://nextstrain-terraform/infra/production/tfstate
2024-04-08 17:28:45      16127 tfstate
```

The remote `tfstate` file was last updated in April...which doesn't sound right considering all of the activity in this repo over the past month.

**Comment by tsibley** [comment]
Ugh, I am.

```
$ envd aws/blab/trs-admin-read-only github/tsibley/nextstrain-admin -- terraform -chdir=env/production workspace list
  default
* trs
```

Dammit. I'll move the state over (tonight or tomorrow morning) and ping here when I do.

**Comment by tsibley** [comment]
Moved with `envd aws/blab/trs github/tsibley/nextstrain-admin -- bash -c 'cd env/production; terraform state pull | (terraform workspace select default && terraform state push -)'`.

@joverlee521 @victorlin What does `plan` say for you now?

**Comment by joverlee521** [comment]
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

🎉

**Comment by tsibley** [comment]
Excellent. Sorry for the hiccups!

**Comment by tsibley** [comment]
(Need to get the current Terraform workspace into my prompt, since "try not to use them much and be careful" hasn't been enough…)
